resources:
  repositories:
    - repository: pos-android
      type: git
      name: pos-android

trigger:
  tags:
    include:
      - '*.*.*'
  branches:
    include:
      - master

pr:
  - '*'

extends:
  template: build.yml@pos-android
  parameters:
    projectAssembleExcludes: ' -x assembleGertec'
    projectBuildExcludes: '-x test -x lint'
    projectTestTask: 'testDebugUnitTest'
    positivoJks: false
    hasArchivesToUpload: false
    hasGoogleServices: false
    projectMainModule: 'app'
    preBuildSteps:
      - task: JavaToolInstaller@0
        displayName: Install Java 17
        inputs:
          versionSpec: '17'
          jdkArchitectureOption: 'x64'
          jdkSourceOption: 'PreInstalled'