[versions]
kotlin = "2.0.0"
gradlePluginVersion = "8.2.1"

[libraries]
gradlePlugin = {group = "com.android.tools.build", name = "gradle", version.ref = "gradlePluginVersion" }
kotlinGradlePlugin = {group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "kotlin" }
[plugins]
org-jetbrains-kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }