[versions]
accompaninsVersion = "0.35.0-alpha"
activityVersion = "1.9.3"
activityComposeVersion = "1.9.3"
appcompatVersion = "1.7.0"
composeBomVersion = "2024.12.01"
constraintLayoutVersion = "2.2.0"
desugarVersion = "2.1.3"
dataContainerDataVersion = "5.0.0-RC18"
dataContainerContractVersion = "5.0.0-RC18"
fragmentVersion = "1.8.2"
gradlePluginVersion = "8.2.2"
kotlinVersion = "2.0.20"
lifecycleVersion = "2.8.7"
materialVersion = "1.12.0"
permissionDispatcherVersion = "4.8.0"
sdkVersion = "6.0.0-alpha32"
sdkDebugVersion = "6.0.0-alpha21"

koinVersion = "4.0.0"
slf4jVersion = "2.0.7"
logbackAndroidVersion = "3.0.0"


[libraries]
activity = { group = "androidx.activity", name = "activity-ktx", version.ref = "activityVersion" }
activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityComposeVersion" }
accompanist-permissions = { group = "com.google.accompanist", name = "accompanist-permissions", version.ref = "accompaninsVersion" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompatVersion" }
compose-bom = { module = "androidx.compose:compose-bom", version.ref = "composeBomVersion" }
compose-material3 = { module = "androidx.compose.material3:material3" }
compose-foundation = { module = "androidx.compose.foundation:foundation" }
compose-ui = { module = "androidx.compose.ui:ui" }
compose-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview" }
compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling" }
constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "constraintLayoutVersion" }
fragment = { group = "androidx.fragment", name = "fragment-ktx", version.ref = "fragmentVersion" }
gradlePlugin = { group = "com.android.tools.build", name = "gradle", version.ref = "gradlePluginVersion" }
koinCore = { group = "io.insert-koin", name = "koin-core", version.ref = "koinVersion" }
koinAndroid = { group = "io.insert-koin", name = "koin-android", version.ref = "koinVersion" }
koinCompose = { group = "io.insert-koin", name = "koin-androidx-compose", version.ref = "koinVersion" }
kotlinGradlePlugin = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "kotlinVersion" }
lifecycle-runtime = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleVersion" }
lifecycle-runtime-compose = { group = "androidx.lifecycle", name = "lifecycle-runtime-compose", version.ref = "lifecycleVersion" }
lifecycle-viewmodel-compose = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-compose", version.ref = "lifecycleVersion" }
material = { group = "com.google.android.material", name = "material", version.ref = "materialVersion" }
permissiondispatcher = { group = "com.github.permissions-dispatcher", name = "permissionsdispatcher", version.ref = "permissionDispatcherVersion" }
permissiondispatcher-processor = { group = "com.github.permissions-dispatcher", name = "permissionsdispatcher-processor", version.ref = "permissionDispatcherVersion" }
tools-desugar = { group = "com.android.tools", name = "desugar_jdk_libs", version.ref = "desugarVersion" }
logbackAndroid = { group = "com.github.tony19", name = "logback-android", version.ref = "logbackAndroidVersion" }
slf4j = { group = "org.slf4j", name = "slf4j-api", version.ref = "slf4jVersion" }

posmobile-datacontainer-data = { group = "co.stone.posmobile", name = "data-container-data", version.ref = "dataContainerDataVersion" }
posmobile-sdk-core = { group = "co.stone.posmobile.sdk", name = "sdk-core", version.ref = "sdkVersion" }
posmobile-sdk-core-android = { group = "co.stone.posmobile.sdk", name = "sdk-core-android", version.ref = "sdkVersion" }
posmobile-sdk-debugmode = { group = "br.com.stone", name = "debugmode", version.ref = "sdkDebugVersion" }

#pos-android-sdk = { group = "br.com.stone", name = "stone-sdk", version.ref = "sdkVersion" }
#pos-android-sdk-debugmode = { group = "br.com.stone.sdk.android", name = "debugmode", version.ref = "sdkVersion" }
#pos-android-sdk-posandroid = { group = "br.com.stone", name = "stone-sdk-posandroid", version.ref = "sdkVersion" }
#pos-android-sdk-posandroid-ingenico = { group = "br.com.stone", name = "stone-sdk-posandroid-ingenico", version.ref = "sdkVersion" }
#pos-android-sdk-posandroid-positivo = { group = "br.com.stone", name = "stone-sdk-posandroid-positivo", version.ref = "sdkVersion" }
#pos-android-sdk-posandroid-gertec = { group = "br.com.stone", name = "stone-sdk-posandroid-gertec", version.ref = "sdkVersion" }
#pos-android-sdk-posandroid-sunmi = { group = "br.com.stone", name = "stone-sdk-posandroid-sunmi", version.ref = "sdkVersion" }

[plugins]
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlinVersion" }
org-jetbrains-kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlinVersion" }
